
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=weather123456
      - MYSQL_DATABASE=task_planner
    ports:
      - 3312:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql # Persist data
  api-app:
    restart: on-failure
    build: .
    ports:
      - 4045:5040
    environment:
      - PORT=5040
      - DB_USERNAME=root
      - DB_PASSWORD=weather123456
      - DB_NAME=DB_NAME=task_planner
      - NODE_ENV=dev
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data: